//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'grammar_oa_main.h'                          *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     january 29th, 2007, at 20h40'9"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

class grammar_oa_main : public C_defaultUserSemanticActions {
  protected : oa_scanner * _mScannerPtr ;
//--- Command line options
  protected : bool mOption_oa_cli_options_createIntermediateFiles ;
  protected : bool mOption_oa_cli_options_forceBalgorithm ;
  protected : bool mOption_oa_cli_options_useCANmaxLegth ;

//--- Constructor
  public : grammar_oa_main (C_galgas_io * inParametersPtr
                                  COMMA_LOCATION_ARGS) ;

  public : void doCompilation (const C_String & inSourceFileName_,
                               const bool inVerboseOptionOn,
                               sint16 & returnCode) ;
//--- START OF USER ZONE 2

//--- Prologue and epilogue
  public : inline void _prologue (void) {}
  public : inline void _epilogue (void) {}

//--- END OF USER ZONE 2

//--- Destructor
  public : virtual ~grammar_oa_main (void) ;
} ;

//---------------------------------------------------------------------------*

