//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'grammar_oa_main.h'                          *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 13th, 2006, at 22h22'45"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

class oa_main : public C_defaultUserSemanticActions {
  protected : oa_scanner * mScannerPtr_ ;
  protected : C_galgas_terminal_io mTerminalIO ;
  protected : C_String mSourceFileExtension_ ;

//--- Command line options
  protected : bool mOption_oa_cli_options_createIntermediateFiles ;
  protected : bool mOption_oa_cli_options_forceBalgorithm ;
  protected : bool mOption_oa_cli_options_useCANmaxLegth ;

//--- Constructor
  public : oa_main (const C_galgas_io_parameters & inIOparameters COMMA_LOCATION_ARGS) ;

  public : void doCompilation (const C_String & inSourceFileName_,
                               sint16 & returnCode) ;
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//--- Destructor
  public : virtual ~oa_main (void) ;
//--- Prologue and epilogue
  public : void _prologue (void) ;
  public : void _epilogue (void) ;
} ;

