//---------------------------------------------------------------------------*
//                                                                           *
//                  File 'include_C_canMessageFromTask.h'                    *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     january 24th, 2010, at 10h7'45"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                abstract class 'cPtr_C_canMessageFromTask'                 *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_canMessageFromTask : public cPtr_AC_canMessage {
  private : typedef cPtr_AC_canMessage inherited ;
//--- START OF USER ZONE 2

  public : virtual bool messageDependsOnTask (void) const ;
  public : virtual bool messageDependsOnMessage (void) const ;
  public : virtual PMUInt32 getMessageDependanceValue (void) const ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_C_canMessageFromTask (const GGS_uint & 
                                COMMA_LOCATION_ARGS) ;

//--- Attributes
  public : GGS_uint  mTaskIndex ;
//--- Class message
  public : virtual const char * instanceMessage (void) const ;
  public : static const char * _static_message (void) ;

//--- Method for 'description' reader
  public : virtual void
  appendForDescription (C_String & ioString,
                        const PMSInt32 inIndentation) const ;

//--- Comparison
  public : virtual bool
  isEqualToObject (const cPtr__AC_galgas_class * inOperand) const ;

//--- Galgas RTTI
  public : virtual AC_galgasClassRunTimeInformationEX * galgasRTTI (void) const ;

//--- Make clone
  public : virtual cPtr__AC_galgas_class * makeClone (void) const ;
} ;

//---------------------------------------------------------------------------*

