//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'include_AC_task.h'                          *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     january 22th, 2007, at 22h16'43"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                      abstract class 'cPtr_AC_task'                        *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_AC_task : public C_GGS_Object {
//--- START OF USER ZONE 2

  public : virtual bool taskDependsOnTask (void) const = 0 ;
  public : virtual bool taskDependsOnMessage (void) const = 0 ;
  public : virtual uint32 getTaskDependanceValue (void) const = 0 ;
  public : virtual uint32 getTaskEveryParameter (void) const = 0 ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_AC_task (LOCATION_ARGS) ;

//--- Declaring a protected virual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_AC_task (void) {}
  #endif

//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const = 0 ;
} ;

//---------------------------------------------------------------------------*

