//---------------------------------------------------------------------------*
//                                                                           *
//                 File 'include_C_canMessageFromMessage.h'                  *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      april 25th, 2006, at 18h47'51"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                   class 'cPtr_C_canMessageFromMessage'                    *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef C_canMessageFromMessage_DEFINED
#define C_canMessageFromMessage_DEFINED

class cPtr_C_canMessageFromMessage : public cPtr_AC_canMessage {
  private : typedef cPtr_AC_canMessage inherited ;
//--- START OF USER ZONE 2

  public : virtual bool messageDependsOnTask (void) const ;
  public : virtual bool messageDependsOnMessage (void) const ;
  public : virtual uint32 getMessageDependanceValue (void) const ;

//--- END OF USER ZONE 2

  public : cPtr_C_canMessageFromMessage (const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mMessageIndex ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

#endif

