//---------------------------------------------------------------------------*
//                                                                           *
//                      File 'include_AC_canMessage.h'                       *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       may 28th, 2006, at 19h38'57"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                   abstract class 'cPtr_AC_canMessage'                     *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_AC_canMessage : public C_GGS_Object {
//--- START OF USER ZONE 2

  public : virtual bool messageDependsOnTask (void) const = 0 ;
  public : virtual bool messageDependsOnMessage (void) const = 0 ;
  public : virtual uint32 getMessageDependanceValue (void) const = 0 ;

//--- END OF USER ZONE 2

  public : cPtr_AC_canMessage (LOCATION_ARGS) ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const = 0 ;
} ;

//---------------------------------------------------------------------------*

