//---------------------------------------------------------------------------*
//                                                                           *
//                File 'include_C_taskDependsFromMessage.h'                  *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 20th, 2006, at 11h47'9"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  class 'cPtr_C_taskDependsFromMessage'                    *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef C_taskDependsFromMessage_DEFINED
#define C_taskDependsFromMessage_DEFINED

class cPtr_C_taskDependsFromMessage : public cPtr_AC_task {
  private : typedef cPtr_AC_task inherited ;
//--- START OF USER ZONE 2

  public : virtual bool taskDependsOnTask (void) const ;
  public : virtual bool taskDependsOnMessage (void) const ;
  public : virtual uint32 getTaskDependanceValue (void) const ;
  public : virtual uint32 getTaskEveryParameter (void) const ;

//--- END OF USER ZONE 2

  public : cPtr_C_taskDependsFromMessage (const GGS_luint & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mMessage ;
  public : GGS_luint  mEvery ;
  public : virtual void appendForDescription (C_String & ioString) const ;
} ;

//---------------------------------------------------------------------------*

#endif

