//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'oa_grammar.cpp'                            *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     november 4th, 2010, at 17h41'15"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*

#include "version_libpm.h"
#if CURRENT_LIBPM_VERSION != VERSION_OF_LIBPM_USED_BY_GALGAS_COMPILER
  #error "This file has been compiled with a version of GALGAS that uses libpm version VERSION_OF_LIBPM_USED_BY_GALGAS_COMPILER, different than the current version (CURRENT_LIBPM_VERSION) of libpm"
#endif

//---------------------------------------------------------------------------*

#include "utilities/MF_MemoryControl.h"

//---------------------------------------------------------------------------*

#include "oa_grammar.h"

//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//              L L ( 1 )    P R O D U C T I O N    R U L E S                *
//                                                                           *
//---------------------------------------------------------------------------*

#define TERMINAL(t)     ((t)+1)
#define NONTERMINAL(nt) ((-nt)-1)
#define END_PRODUCTION  (0)

static const PMSInt16 gProductions [] = {
// At index 0 : <axiome>, in file 'oa_parser.ggs', line 15
  TERMINAL (C_Lexique_oa_5F_scanner::kToken_system) // $system$
, NONTERMINAL (1) // <select_oa_5F_parser_0>
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_end) // $end$
, END_PRODUCTION
//---- Added productions from 'select' and 'repeat' instructions
// At index 4 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
, END_PRODUCTION
// At index 5 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_processor) // $processor$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, NONTERMINAL (2) // <select_oa_5F_parser_1>
, TERMINAL (C_Lexique_oa_5F_scanner::kToken__3B_) // $;$
, NONTERMINAL (1) // <select_oa_5F_parser_0>
, END_PRODUCTION
// At index 11 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
, NONTERMINAL (3) // <select_oa_5F_parser_2>
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_network) // $network$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, NONTERMINAL (4) // <select_oa_5F_parser_3>
, TERMINAL (C_Lexique_oa_5F_scanner::kToken__3B_) // $;$
, NONTERMINAL (1) // <select_oa_5F_parser_0>
, END_PRODUCTION
// At index 18 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_task) // $task$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_priority) // $priority$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_duration) // $duration$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken__2E__2E_) // $..$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, NONTERMINAL (5) // <select_oa_5F_parser_4>
, NONTERMINAL (6) // <select_oa_5F_parser_5>
, NONTERMINAL (7) // <select_oa_5F_parser_6>
, TERMINAL (C_Lexique_oa_5F_scanner::kToken__3B_) // $;$
, NONTERMINAL (1) // <select_oa_5F_parser_0>
, END_PRODUCTION
// At index 32 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
, NONTERMINAL (11) // <select_oa_5F_parser_10>
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_network) // $network$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_length) // $length$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_priority) // $priority$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, NONTERMINAL (12) // <select_oa_5F_parser_11>
, NONTERMINAL (13) // <select_oa_5F_parser_12>
, NONTERMINAL (14) // <select_oa_5F_parser_13>
, TERMINAL (C_Lexique_oa_5F_scanner::kToken__3B_) // $;$
, NONTERMINAL (1) // <select_oa_5F_parser_0>
, END_PRODUCTION
// At index 46 : <select_oa_5F_parser_1>, in file 'oa_parser.ggs', line 29
, END_PRODUCTION
// At index 47 : <select_oa_5F_parser_1>, in file 'oa_parser.ggs', line 29
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_scalingfactor) // $scalingfactor$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 50 : <select_oa_5F_parser_2>, in file 'oa_parser.ggs', line 42
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_can) // $can$
, END_PRODUCTION
// At index 52 : <select_oa_5F_parser_2>, in file 'oa_parser.ggs', line 42
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_van) // $van$
, END_PRODUCTION
// At index 54 : <select_oa_5F_parser_3>, in file 'oa_parser.ggs', line 53
, END_PRODUCTION
// At index 55 : <select_oa_5F_parser_3>, in file 'oa_parser.ggs', line 53
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_scalingfactor) // $scalingfactor$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 58 : <select_oa_5F_parser_4>, in file 'oa_parser.ggs', line 79
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_offset) // $offset$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 61 : <select_oa_5F_parser_4>, in file 'oa_parser.ggs', line 79
, END_PRODUCTION
// At index 62 : <select_oa_5F_parser_5>, in file 'oa_parser.ggs', line 88
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_deadline) // $deadline$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 65 : <select_oa_5F_parser_5>, in file 'oa_parser.ggs', line 88
, END_PRODUCTION
// At index 66 : <select_oa_5F_parser_6>, in file 'oa_parser.ggs', line 97
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_period) // $period$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_processor) // $processor$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, END_PRODUCTION
// At index 71 : <select_oa_5F_parser_6>, in file 'oa_parser.ggs', line 97
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_on) // $on$
, NONTERMINAL (8) // <select_oa_5F_parser_7>
, END_PRODUCTION
// At index 74 : <select_oa_5F_parser_7>, in file 'oa_parser.ggs', line 110
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_task) // $task$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, NONTERMINAL (9) // <select_oa_5F_parser_8>
, END_PRODUCTION
// At index 78 : <select_oa_5F_parser_7>, in file 'oa_parser.ggs', line 110
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_message) // $message$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_processor) // $processor$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, NONTERMINAL (10) // <select_oa_5F_parser_9>
, END_PRODUCTION
// At index 84 : <select_oa_5F_parser_8>, in file 'oa_parser.ggs', line 115
, END_PRODUCTION
// At index 85 : <select_oa_5F_parser_8>, in file 'oa_parser.ggs', line 115
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_every) // $every$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 88 : <select_oa_5F_parser_9>, in file 'oa_parser.ggs', line 134
, END_PRODUCTION
// At index 89 : <select_oa_5F_parser_9>, in file 'oa_parser.ggs', line 134
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_every) // $every$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 92 : <select_oa_5F_parser_10>, in file 'oa_parser.ggs', line 156
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_standard) // $standard$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_message) // $message$
, END_PRODUCTION
// At index 95 : <select_oa_5F_parser_10>, in file 'oa_parser.ggs', line 156
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_extended) // $extended$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_message) // $message$
, END_PRODUCTION
// At index 98 : <select_oa_5F_parser_10>, in file 'oa_parser.ggs', line 156
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_message) // $message$
, END_PRODUCTION
// At index 100 : <select_oa_5F_parser_11>, in file 'oa_parser.ggs', line 194
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_offset) // $offset$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 103 : <select_oa_5F_parser_11>, in file 'oa_parser.ggs', line 194
, END_PRODUCTION
// At index 104 : <select_oa_5F_parser_12>, in file 'oa_parser.ggs', line 203
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_deadline) // $deadline$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 107 : <select_oa_5F_parser_12>, in file 'oa_parser.ggs', line 203
, END_PRODUCTION
// At index 108 : <select_oa_5F_parser_13>, in file 'oa_parser.ggs', line 211
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_period) // $period$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_literal_5F_integer) // $literal_integer$
, END_PRODUCTION
// At index 111 : <select_oa_5F_parser_13>, in file 'oa_parser.ggs', line 211
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_on) // $on$
, NONTERMINAL (15) // <select_oa_5F_parser_14>
, END_PRODUCTION
// At index 114 : <select_oa_5F_parser_14>, in file 'oa_parser.ggs', line 220
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_message) // $message$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, END_PRODUCTION
// At index 117 : <select_oa_5F_parser_14>, in file 'oa_parser.ggs', line 220
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_task) // $task$
, TERMINAL (C_Lexique_oa_5F_scanner::kToken_identifier) // $identifier$
, END_PRODUCTION
// At index 120 : <>, in file '.ggs', line 0
, NONTERMINAL (0) // <axiome>
, END_PRODUCTION
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                     P R O D U C T I O N    N A M E S                      *
//                                                                           *
//---------------------------------------------------------------------------*

static const cProductionNameDescriptor gProductionNames [36] = {
 {"<axiome>", "oa_parser", 0}, // at index 0
 {"<select_oa_5F_parser_0>", "oa_parser", 4}, // at index 1
 {"<select_oa_5F_parser_0>", "oa_parser", 5}, // at index 2
 {"<select_oa_5F_parser_0>", "oa_parser", 11}, // at index 3
 {"<select_oa_5F_parser_0>", "oa_parser", 18}, // at index 4
 {"<select_oa_5F_parser_0>", "oa_parser", 32}, // at index 5
 {"<select_oa_5F_parser_1>", "oa_parser", 46}, // at index 6
 {"<select_oa_5F_parser_1>", "oa_parser", 47}, // at index 7
 {"<select_oa_5F_parser_2>", "oa_parser", 50}, // at index 8
 {"<select_oa_5F_parser_2>", "oa_parser", 52}, // at index 9
 {"<select_oa_5F_parser_3>", "oa_parser", 54}, // at index 10
 {"<select_oa_5F_parser_3>", "oa_parser", 55}, // at index 11
 {"<select_oa_5F_parser_4>", "oa_parser", 58}, // at index 12
 {"<select_oa_5F_parser_4>", "oa_parser", 61}, // at index 13
 {"<select_oa_5F_parser_5>", "oa_parser", 62}, // at index 14
 {"<select_oa_5F_parser_5>", "oa_parser", 65}, // at index 15
 {"<select_oa_5F_parser_6>", "oa_parser", 66}, // at index 16
 {"<select_oa_5F_parser_6>", "oa_parser", 71}, // at index 17
 {"<select_oa_5F_parser_7>", "oa_parser", 74}, // at index 18
 {"<select_oa_5F_parser_7>", "oa_parser", 78}, // at index 19
 {"<select_oa_5F_parser_8>", "oa_parser", 84}, // at index 20
 {"<select_oa_5F_parser_8>", "oa_parser", 85}, // at index 21
 {"<select_oa_5F_parser_9>", "oa_parser", 88}, // at index 22
 {"<select_oa_5F_parser_9>", "oa_parser", 89}, // at index 23
 {"<select_oa_5F_parser_10>", "oa_parser", 92}, // at index 24
 {"<select_oa_5F_parser_10>", "oa_parser", 95}, // at index 25
 {"<select_oa_5F_parser_10>", "oa_parser", 98}, // at index 26
 {"<select_oa_5F_parser_11>", "oa_parser", 100}, // at index 27
 {"<select_oa_5F_parser_11>", "oa_parser", 103}, // at index 28
 {"<select_oa_5F_parser_12>", "oa_parser", 104}, // at index 29
 {"<select_oa_5F_parser_12>", "oa_parser", 107}, // at index 30
 {"<select_oa_5F_parser_13>", "oa_parser", 108}, // at index 31
 {"<select_oa_5F_parser_13>", "oa_parser", 111}, // at index 32
 {"<select_oa_5F_parser_14>", "oa_parser", 114}, // at index 33
 {"<select_oa_5F_parser_14>", "oa_parser", 117}, // at index 34
 {"<>", "", 120} // at index 35
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//            L L ( 1 )    P R O D U C T I O N    I N D E X E S              *
//                                                                           *
//---------------------------------------------------------------------------*

static const PMSInt16 gProductionIndexes [36] = {
0, // index 0 : <axiome>, in file 'oa_parser.ggs', line 15
4, // index 1 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
5, // index 2 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
11, // index 3 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
18, // index 4 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
32, // index 5 : <select_oa_5F_parser_0>, in file 'oa_parser.ggs', line 23
46, // index 6 : <select_oa_5F_parser_1>, in file 'oa_parser.ggs', line 29
47, // index 7 : <select_oa_5F_parser_1>, in file 'oa_parser.ggs', line 29
50, // index 8 : <select_oa_5F_parser_2>, in file 'oa_parser.ggs', line 42
52, // index 9 : <select_oa_5F_parser_2>, in file 'oa_parser.ggs', line 42
54, // index 10 : <select_oa_5F_parser_3>, in file 'oa_parser.ggs', line 53
55, // index 11 : <select_oa_5F_parser_3>, in file 'oa_parser.ggs', line 53
58, // index 12 : <select_oa_5F_parser_4>, in file 'oa_parser.ggs', line 79
61, // index 13 : <select_oa_5F_parser_4>, in file 'oa_parser.ggs', line 79
62, // index 14 : <select_oa_5F_parser_5>, in file 'oa_parser.ggs', line 88
65, // index 15 : <select_oa_5F_parser_5>, in file 'oa_parser.ggs', line 88
66, // index 16 : <select_oa_5F_parser_6>, in file 'oa_parser.ggs', line 97
71, // index 17 : <select_oa_5F_parser_6>, in file 'oa_parser.ggs', line 97
74, // index 18 : <select_oa_5F_parser_7>, in file 'oa_parser.ggs', line 110
78, // index 19 : <select_oa_5F_parser_7>, in file 'oa_parser.ggs', line 110
84, // index 20 : <select_oa_5F_parser_8>, in file 'oa_parser.ggs', line 115
85, // index 21 : <select_oa_5F_parser_8>, in file 'oa_parser.ggs', line 115
88, // index 22 : <select_oa_5F_parser_9>, in file 'oa_parser.ggs', line 134
89, // index 23 : <select_oa_5F_parser_9>, in file 'oa_parser.ggs', line 134
92, // index 24 : <select_oa_5F_parser_10>, in file 'oa_parser.ggs', line 156
95, // index 25 : <select_oa_5F_parser_10>, in file 'oa_parser.ggs', line 156
98, // index 26 : <select_oa_5F_parser_10>, in file 'oa_parser.ggs', line 156
100, // index 27 : <select_oa_5F_parser_11>, in file 'oa_parser.ggs', line 194
103, // index 28 : <select_oa_5F_parser_11>, in file 'oa_parser.ggs', line 194
104, // index 29 : <select_oa_5F_parser_12>, in file 'oa_parser.ggs', line 203
107, // index 30 : <select_oa_5F_parser_12>, in file 'oa_parser.ggs', line 203
108, // index 31 : <select_oa_5F_parser_13>, in file 'oa_parser.ggs', line 211
111, // index 32 : <select_oa_5F_parser_13>, in file 'oa_parser.ggs', line 211
114, // index 33 : <select_oa_5F_parser_14>, in file 'oa_parser.ggs', line 220
117, // index 34 : <select_oa_5F_parser_14>, in file 'oa_parser.ggs', line 220
120 // index 35 : <>, in file '.ggs', line 0
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//      L L ( 1 )    F I R S T    P R O D U C T I O N    I N D E X E S       *
//                                                                           *
//---------------------------------------------------------------------------*

static const PMSInt16 gFirstProductionIndexes [18] = {
0, // at 0 : <axiome>
1, // at 1 : <select_oa_5F_parser_0>
6, // at 2 : <select_oa_5F_parser_1>
8, // at 3 : <select_oa_5F_parser_2>
10, // at 4 : <select_oa_5F_parser_3>
12, // at 5 : <select_oa_5F_parser_4>
14, // at 6 : <select_oa_5F_parser_5>
16, // at 7 : <select_oa_5F_parser_6>
18, // at 8 : <select_oa_5F_parser_7>
20, // at 9 : <select_oa_5F_parser_8>
22, // at 10 : <select_oa_5F_parser_9>
24, // at 11 : <select_oa_5F_parser_10>
27, // at 12 : <select_oa_5F_parser_11>
29, // at 13 : <select_oa_5F_parser_12>
31, // at 14 : <select_oa_5F_parser_13>
33, // at 15 : <select_oa_5F_parser_14>
35, // at 16 : <>
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//               L L ( 1 )    D E C I S I O N    T A B L E S                 *
//                                                                           *
//---------------------------------------------------------------------------*

static const PMSInt16 gDecision [] = {
// At index 0 : <axiome> only one production, no choice
  -1,
//---- Added non terminal symbols from 'select' and 'repeat' instructions
// At index 1 : <select_oa_5F_parser_0>
C_Lexique_oa_5F_scanner::kToken_end, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_processor, -1, // Choice 2
C_Lexique_oa_5F_scanner::kToken_can, C_Lexique_oa_5F_scanner::kToken_van, -1, // Choice 3
C_Lexique_oa_5F_scanner::kToken_task, -1, // Choice 4
C_Lexique_oa_5F_scanner::kToken_message, C_Lexique_oa_5F_scanner::kToken_standard, C_Lexique_oa_5F_scanner::kToken_extended, -1, // Choice 5
  -1,
// At index 15 : <select_oa_5F_parser_1>
C_Lexique_oa_5F_scanner::kToken__3B_, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_scalingfactor, -1, // Choice 2
  -1,
// At index 20 : <select_oa_5F_parser_2>
C_Lexique_oa_5F_scanner::kToken_can, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_van, -1, // Choice 2
  -1,
// At index 25 : <select_oa_5F_parser_3>
C_Lexique_oa_5F_scanner::kToken__3B_, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_scalingfactor, -1, // Choice 2
  -1,
// At index 30 : <select_oa_5F_parser_4>
C_Lexique_oa_5F_scanner::kToken_offset, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_deadline, C_Lexique_oa_5F_scanner::kToken_period, C_Lexique_oa_5F_scanner::kToken_on, -1, // Choice 2
  -1,
// At index 37 : <select_oa_5F_parser_5>
C_Lexique_oa_5F_scanner::kToken_deadline, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_period, C_Lexique_oa_5F_scanner::kToken_on, -1, // Choice 2
  -1,
// At index 43 : <select_oa_5F_parser_6>
C_Lexique_oa_5F_scanner::kToken_period, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_on, -1, // Choice 2
  -1,
// At index 48 : <select_oa_5F_parser_7>
C_Lexique_oa_5F_scanner::kToken_task, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_message, -1, // Choice 2
  -1,
// At index 53 : <select_oa_5F_parser_8>
C_Lexique_oa_5F_scanner::kToken__3B_, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_every, -1, // Choice 2
  -1,
// At index 58 : <select_oa_5F_parser_9>
C_Lexique_oa_5F_scanner::kToken__3B_, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_every, -1, // Choice 2
  -1,
// At index 63 : <select_oa_5F_parser_10>
C_Lexique_oa_5F_scanner::kToken_standard, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_extended, -1, // Choice 2
C_Lexique_oa_5F_scanner::kToken_message, -1, // Choice 3
  -1,
// At index 70 : <select_oa_5F_parser_11>
C_Lexique_oa_5F_scanner::kToken_offset, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_deadline, C_Lexique_oa_5F_scanner::kToken_period, C_Lexique_oa_5F_scanner::kToken_on, -1, // Choice 2
  -1,
// At index 77 : <select_oa_5F_parser_12>
C_Lexique_oa_5F_scanner::kToken_deadline, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_period, C_Lexique_oa_5F_scanner::kToken_on, -1, // Choice 2
  -1,
// At index 83 : <select_oa_5F_parser_13>
C_Lexique_oa_5F_scanner::kToken_period, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_on, -1, // Choice 2
  -1,
// At index 88 : <select_oa_5F_parser_14>
C_Lexique_oa_5F_scanner::kToken_message, -1, // Choice 1
C_Lexique_oa_5F_scanner::kToken_task, -1, // Choice 2
  -1,
// At index 93 : <> only one production, no choice
  -1,
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//       L L ( 1 )    D E C I S I O N    T A B L E S    I N D E X E S        *
//                                                                           *
//---------------------------------------------------------------------------*

static const PMSInt16 gDecisionIndexes [18] = {
0, // at 0 : <axiome>
1, // at 1 : <select_oa_5F_parser_0>
15, // at 2 : <select_oa_5F_parser_1>
20, // at 3 : <select_oa_5F_parser_2>
25, // at 4 : <select_oa_5F_parser_3>
30, // at 5 : <select_oa_5F_parser_4>
37, // at 6 : <select_oa_5F_parser_5>
43, // at 7 : <select_oa_5F_parser_6>
48, // at 8 : <select_oa_5F_parser_7>
53, // at 9 : <select_oa_5F_parser_8>
58, // at 10 : <select_oa_5F_parser_9>
63, // at 11 : <select_oa_5F_parser_10>
70, // at 12 : <select_oa_5F_parser_11>
77, // at 13 : <select_oa_5F_parser_12>
83, // at 14 : <select_oa_5F_parser_13>
88, // at 15 : <select_oa_5F_parser_14>
93, // at 16 : <>
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                   'axiome' non terminal implementation                    *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_oa_5F_grammar::nt_axiome_ (C_Lexique_oa_5F_scanner * inLexique) {
  rule_oa_5F_parser_axiome_i0_(inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                   Grammar start symbol implementation                     *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_oa_5F_grammar::_performSourceFileParsing_ (C_Compiler * inCompiler,
                                GALGAS_lstring inFilePath
                                COMMA_LOCATION_ARGS) {
  if (inFilePath.isValid ()) {
    const GALGAS_string filePathAsString = inFilePath.reader_string (HERE) ;
    C_String filePath = filePathAsString.stringValue () ;
    if (! filePath.isAbsolutePath ()) {
      filePath = inCompiler->sourceFileName ().stringByDeletingLastPathComponent ().stringByAppendingPathComponent (filePath) ;
    }
    if (filePath.fileExists ()) {
    C_Lexique_oa_5F_scanner * scanner = NULL ;
    macroMyNew (scanner, C_Lexique_oa_5F_scanner (inCompiler, "", "", inCompiler->ioParametersPtr (), filePath COMMA_HERE)) ;
    // if (scanner->needsCompiling ()) {
      if (scanner->sourceText () != NULL) {
        scanner->mPerformGeneration = inCompiler->mPerformGeneration ;
        const bool ok = scanner->performTopDownParsing (gProductions, gProductionNames, gProductionIndexes,
                                                         gFirstProductionIndexes, gDecision, gDecisionIndexes, 120) ;
        if (ok && ! scanner->mParseOnlyFlag) {
          cGrammar_oa_5F_grammar grammar ;
          grammar.nt_axiome_ (scanner) ;
        }
      }else{
        C_String message ;
        message << "the '" << filePath << "' file exists, but cannot be read" ;
        const GALGAS_location errorLocation (inFilePath.reader_location (THERE)) ;
        inCompiler->semanticErrorAtLocation (errorLocation, message COMMA_THERE) ;
      }
    // }
    macroReleaseObject (scanner) ;
  }else{
    C_String message ;
    message << "the '" << filePath << "' file does not exist" ;
    const GALGAS_location errorLocation (inFilePath.reader_location (THERE)) ;
    inCompiler->semanticErrorAtLocation (errorLocation, message COMMA_THERE) ;
    }
  }
}

//---------------------------------------------------------------------------*

void cGrammar_oa_5F_grammar::_performSourceStringParsing_ (C_Compiler * inCompiler,
                                GALGAS_string inSourceString
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (inSourceString.isValid ()) {
    const C_String sourceString = inSourceString.stringValue () ;
    C_Lexique_oa_5F_scanner * scanner = NULL ;
    macroMyNew (scanner, C_Lexique_oa_5F_scanner (inCompiler, inCompiler->ioParametersPtr (), sourceString, "Error when parsing dynamic string" COMMA_HERE)) ;
    scanner->mPerformGeneration = inCompiler->mPerformGeneration ;
    const bool ok = scanner->performTopDownParsing (gProductions, gProductionNames, gProductionIndexes,
                                                    gFirstProductionIndexes, gDecision, gDecisionIndexes, 120) ;
    if (ok && ! scanner->mParseOnlyFlag) {
      cGrammar_oa_5F_grammar grammar ;
      grammar.nt_axiome_ (scanner) ;
    }
    macroReleaseObject (scanner) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_0' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_0 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_1' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_1 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_2' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_2 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_3' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_3 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_4' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_4 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_5' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_5 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_6' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_6 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_7' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_7 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_8' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_8 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_9' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_9 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_10' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_10 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_11' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_11 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_12' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_12 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_13' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_13 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_oa_5F_parser_14' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_oa_5F_grammar::select_oa_5F_parser_14 (C_Lexique_oa_5F_scanner * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*

