//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'oa_grammar.h'                             *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     october 11th, 2009, at 11h51'12"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef GRAMMAR_oa_grammar_HAS_BEEN_DEFINED
#define GRAMMAR_oa_grammar_HAS_BEEN_DEFINED

//---------------------------------------------------------------------------*

#include "oa_parser.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*

class oa_grammar : public oa_parser {
  public : virtual void nt_axiome_ (oa_scanner &) ;
  public : static void _performSourceFileParsing_ (C_Compiler & inCompiler,
                                const C_String & inDependancyExtension,
                                const C_String & inDependancyPath,
                                GGS_string * inSentStringPtr,
                                const GGS_lstring inFileName
                                COMMA_LOCATION_ARGS) ;
  public : static void _performSourceStringParsing_ (C_Compiler & inCompiler,
                                GGS_string * inSentStringPtr,
                                const GGS_string inSourceString
                                COMMA_LOCATION_ARGS) ;
  public : virtual PMSInt16 select_repeat_oa_parser_0 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_1 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_2 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_3 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_4 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_5 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_6 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_7 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_8 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_9 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_10 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_11 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_12 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_13 (oa_scanner &) ;
  public : virtual PMSInt16 select_oa_parser_14 (oa_scanner &) ;
} ;

//---------------------------------------------------------------------------*

#endif
