//---------------------------------------------------------------------------*
//                                                                           *
//                             File 'oa_main.h'                              *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     january 17th, 2007, at 19h44'28"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef INTERFACE_oa_main_DEFINED
#define INTERFACE_oa_main_DEFINED

//---------------------------------------------------------------------------*

#include "oa_grammar.h"
#include "oa_scanner.h"
#include "oa_cli_options.h"
#include "galgas/C_galgas_terminal_io.h"
#include "galgas/C_galgas_CLI_Options.h"
#include "command_line_interface/C_CLI_OptionGroup.h"
#include "command_line_interface/C_builtin_CLI_Options.h"

//---------------------------------------------------------------------------*

#include "grammar_oa_main.h"

class C_options_for_oa_main : public C_CLI_OptionGroup {
//--- Constructor
  public : C_options_for_oa_main (const bool inAcceptsDebugOption) ;

//--- Included options
  private : C_builtin_CLI_Options mBuiltinOptions ;
  private : C_galgas_CLI_Options mGalgasOptions ;
  private : oa_cli_options mOptions_oa_cli_options; 
} ;

//---------------------------------------------------------------------------*

void oa_main_prologue (const C_options_for_oa_main & inOptions,
                                      const TC_UniqueArray <C_String> & inSourceFilesArray) ;

void oa_main_epilogue (const C_options_for_oa_main & inOptions) ;


//---------------------------------------------------------------------------*

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*

#endif
