//---------------------------------------------------------------------------*
//                                                                           *
//                             File 'oa_main.h'                              *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     november 4th, 2010, at 17h41'25"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef oa_main_ENTITIES_DEFINED
#define oa_main_ENTITIES_DEFINED

//---------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*

class GALGAS__32_stringlist ;
class GALGAS_char ;
class GALGAS_string ;
class GALGAS_application ;
class GALGAS_type ;
class GALGAS_object ;
class GALGAS_stringlist ;
class GALGAS_bool ;
class GALGAS_filewrapper ;
class GALGAS_uint ;
class GALGAS_sint ;
class GALGAS_uint_36__34_ ;
class GALGAS_sint_36__34_ ;
class GALGAS_double ;
class GALGAS_location ;
class GALGAS_stringset ;
class GALGAS_functionlist ;
class GALGAS_function ;
class GALGAS_typelist ;
class GALGAS_objectlist ;
class GALGAS_binaryset ;
class GALGAS_uint_36__34_list ;
class GALGAS_data ;
class GALGAS_luint ;
class GALGAS_luintlist ;
class GALGAS_uintlist ;
class GALGAS_lstring ;
class GALGAS_lstringlist ;
class GALGAS_lbool ;
class GALGAS_luint_36__34_ ;
class GALGAS_lsint ;
class GALGAS_lsint_36__34_ ;
class GALGAS_lchar ;
class GALGAS_ldouble ;

//---------------------------------------------------------------------------*
//                                                                           *
//                             Routine 'before'                              *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_before (C_Compiler * inCompiler
                     COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Routine 'programRule_0'                          *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_programRule_5F__30_ (const GALGAS_lstring constinArgument0,
                                  C_Compiler * inCompiler
                                  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                              Routine 'after'                              *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_after (C_Compiler * inCompiler
                    COMMA_LOCATION_ARGS) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

#endif
