//---------------------------------------------------------------------------*
//                                                                           *
//                            File 'oa_parser.h'                             *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     february 7th, 2010, at 20h59'26"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef oa_parser_DEFINED
#define oa_parser_DEFINED

#include <string.h>

//---------------------------------------------------------------------------*

#include "galgas/GGS__header.h"
#include "oa_scanner.h"

//---------------------------------------------------------------------------*

// Include imported semantics
#include "oa_semantics.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//                    Parser class oa_parser declaration                     *
//                                                                           *
//---------------------------------------------------------------------------*

class oa_parser {
  public : virtual ~oa_parser (void) {}

  protected : virtual void nt_axiome_ (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : void pr_axiome_oa_parser_14_13_ (C_Lexique_oa_5F_scanner &) ;

  protected : virtual PMSInt16 select_oa_5F_parser_0 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_1 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_2 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_3 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_4 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_5 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_6 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_7 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_8 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_9 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_10 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_11 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_12 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_13 (C_Lexique_oa_5F_scanner &) = 0 ;

  protected : virtual PMSInt16 select_oa_5F_parser_14 (C_Lexique_oa_5F_scanner &) = 0 ;

} ;

//---------------------------------------------------------------------------*

#endif
