//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'oa_scanner.h'                             *
//               Generated by version 0.14.0 (LL(1) grammar)                 *
//                     january 17th, 2005, at 13h54'53"                      *
//                                                                           *
// This program is free software; you can redistribute it and/or modify it   *
// under the terms of the GNU General Public License as published by the     *
// Free Software Foundation.                                                 *
//                                                                           *
// This program is distributed in the hope it will be useful, but WITHOUT    *
// ANY WARRANTY; without even the implied warranty of MERCHANDIBILITY or     *
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for  *
// more details.                                                             *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef oa_scanner_0_DEFINED
#define oa_scanner_0_DEFINED
#include "galgas/C_lexique.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Lexical scanner class                            *
//                                                                           *
//---------------------------------------------------------------------------*

class oa_scanner : public C_lexique {
// Terminal symbols enumeration
  public : enum {oa_scanner_1_,
  oa_scanner_1_identifier,
  oa_scanner_1_system,
  oa_scanner_1_end,
  oa_scanner_1_task,
  oa_scanner_1_standard,
  oa_scanner_1_extended,
  oa_scanner_1_message,
  oa_scanner_1_length,
  oa_scanner_1_priority,
  oa_scanner_1_period,
  oa_scanner_1_offset,
  oa_scanner_1_on,
  oa_scanner_1_deadline,
  oa_scanner_1_duration,
  oa_scanner_1_processor,
  oa_scanner_1_can,
  oa_scanner_1_van,
  oa_scanner_1_network,
  oa_scanner_1_factor,
  oa_scanner_1_step,
  oa_scanner_1_every,
  oa_scanner_1__2C,
  oa_scanner_1__3B,
  oa_scanner_1__2E_2E,
  oa_scanner_1_literal_5Finteger} ;

//--- Key words table 'keyWordList'
  public : static const sint16 oa_scanner_table_size_keyWordList ;
  private : static const C_lexique_table_entry oa_scanner_table_for_keyWordList [20] ;
  public : static sint16 search_into_keyWordList (const C_string & inSearchedString) ;

//--- Key words table 'delimitorsList'
  public : static const sint16 oa_scanner_table_size_delimitorsList ;
  private : static const C_lexique_table_entry oa_scanner_table_for_delimitorsList [3] ;
  public : static sint16 search_into_delimitorsList (const C_string & inSearchedString) ;

  protected : virtual void parseLexicalToken (const bool inPropagateLexicaleErrorException) ;
  protected : virtual void appendTerminalMessageToSyntaxErrorMessage (const sint16 numeroTerminal,
                                                              C_string & messageErreur) ;

//--- Constructor
  public : oa_scanner (AC_galgas_io * inGalgasInputOutput) ;
  public : uint32 ulongValue ; // user defined attribute
  public : C_string identifierString ; // user defined attribute
  public : virtual sint16 getTerminalVocabularyCount_ (void) const { return 25 ; }

  public : static sint32 getStylesCount (void) ;
  public : static const char * getStyleName (const sint32 inIndex) ;
//--- Virtual method called getting terminal style index
  public : virtual uint8 getTerminalStyleIndex (const sint32 inTerminal) ;
} ;

//---------------------------------------------------------------------------*

#endif
