//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'oa_scanner.h'                             *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     december 6th, 2006, at 21h51'45"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef oa_scanner_0_DEFINED
#define oa_scanner_0_DEFINED
#include "galgas/C_Lexique.h"

//---------------------------------------------------------------------------*
//                                                                           *
//                          Lexical scanner class                            *
//                                                                           *
//---------------------------------------------------------------------------*

class cTokenFor_oa_scanner : public cToken {
  public : C_String identifierString ; // user defined attribute
  public : uint32 ulongValue ; // user defined attribute
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Lexical scanner class                            *
//                                                                           *
//---------------------------------------------------------------------------*

class oa_scanner : public C_Lexique {
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//--- Terminal symbols enumeration
  public : enum {oa_scanner_1_,
  oa_scanner_1_identifier,
  oa_scanner_1_system,
  oa_scanner_1_end,
  oa_scanner_1_task,
  oa_scanner_1_standard,
  oa_scanner_1_extended,
  oa_scanner_1_message,
  oa_scanner_1_length,
  oa_scanner_1_priority,
  oa_scanner_1_period,
  oa_scanner_1_offset,
  oa_scanner_1_on,
  oa_scanner_1_deadline,
  oa_scanner_1_duration,
  oa_scanner_1_processor,
  oa_scanner_1_can,
  oa_scanner_1_van,
  oa_scanner_1_network,
  oa_scanner_1_scalingfactor,
  oa_scanner_1_every,
  oa_scanner_1__2C,
  oa_scanner_1__3B,
  oa_scanner_1__2E_2E,
  oa_scanner_1_literal_5Finteger} ;

//--- Key words table 'delimitorsList'
  public : static const sint16 oa_scanner_table_size_delimitorsList ;
  private : static const C_lexique_table_entry oa_scanner_table_for_delimitorsList [3] ;
  public : static sint16 search_into_delimitorsList (const C_String & inSearchedString) ;

//--- Key words table 'keyWordList'
  public : static const sint16 oa_scanner_table_size_keyWordList ;
  private : static const C_lexique_table_entry oa_scanner_table_for_keyWordList [19] ;
  public : static sint16 search_into_keyWordList (const C_String & inSearchedString) ;

  protected : virtual void parseLexicalToken (const bool inPropagateLexicalErrorException) ;
  protected : virtual void appendTerminalMessageToSyntaxErrorMessage (const sint16 numeroTerminal,
                                                              C_String & messageErreur) ;

//--- Constructor
  public : oa_scanner (AC_galgas_io * inGalgasInputOutput COMMA_LOCATION_ARGS) ;
  public : C_String identifierString ; // user defined attribute
  public : uint32 ulongValue ; // user defined attribute
  public : virtual sint16 terminalVocabularyCount (void) const { return 24 ; }

//--- Get Token String
  public : virtual C_String getCurrentTokenString (const sint16 inTokenCode) const ;
//--- Enter Token
  protected : void _enterToken (const sint16 inTokenCode) ;
//--- Restore context from oken
  protected : virtual void _restoreContextFromToken (void) ;
//--- Style Definition
  public : static sint32 getStylesCount (void) ;
  public : static const char * getStyleName (const sint32 inIndex) ;
  public : static const char * getStyleIdentifier (const sint32 inIndex) ;
//--- Virtual method called getting terminal style index
  public : virtual uint8 terminalStyleIndex (const sint32 inTerminal) ;
} ;

//---------------------------------------------------------------------------*

#endif
