//---------------------------------------------------------------------------*
//                                                                           *
//                  File 'separateHeaderFor_AC_5F_task.h'                    *
//             Generated by version version GALGAS_BETA_VERSION              *
//                      july 16th, 2011, at 15h22'10"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     Pointer class for @AC_task class                      *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_AC_5F_task : public acPtr_class {
//--- START OF USER ZONE 2

  public : virtual bool taskDependsOnTask (void) const = 0 ;
  public : virtual bool taskDependsOnMessage (void) const = 0 ;
  public : virtual PMUInt32 getTaskDependanceValue (void) const = 0 ;
  public : virtual PMUInt32 getTaskEveryParameter (void) const = 0 ;

//--- END OF USER ZONE 2

//--- Attributes

//--- Constructor
  public : cPtr_AC_5F_task (LOCATION_ARGS) ;

//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const = 0 ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const = 0 ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const = 0 ;

} ;

