//-----------------------------------------------------------------------------*
//                                                                             *
//           File 'separateHeaderFor_C_5F_canMessageFromMessage.h'             *
//                         Generated by version 2.6.0                          *
//                       july 15th, 2014, at 17h34'32"                         *
//                                                                             *
//-----------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//-----------------------------------------------------------------------------*
//                                                                             *
//              Pointer class for @C_canMessageFromMessage class               *
//                                                                             *
//-----------------------------------------------------------------------------*

class cPtr_C_5F_canMessageFromMessage : public cPtr_AC_5F_canMessage {
//--- START OF USER ZONE 2

  public : virtual bool messageDependsOnTask (void) const ;
  public : virtual bool messageDependsOnMessage (void) const ;
  public : virtual uint32_t getMessageDependanceValue (void) const ;

//--- END OF USER ZONE 2

//--- Attributes
  public : GALGAS_uint mAttribute_mMessageIndex ;

//--- Constructor
  public : cPtr_C_5F_canMessageFromMessage (const GALGAS_uint & in_mMessageIndex
                                            COMMA_LOCATION_ARGS) ;

//--- Attribute accessors
  public : VIRTUAL_IN_DEBUG GALGAS_uint reader_mMessageIndex (UNUSED_LOCATION_ARGS) const ;
//--- Description
  public : virtual void description (C_String & ioString,
                                     const int32_t inIndentation) const ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

