//---------------------------------------------------------------------------*
//                                                                           *
//               File 'separateHeaderFor_AC_5F_canMessage.h'                 *
//             Generated by version version GALGAS_BETA_VERSION              *
//                      april 26th, 2012, at 18h9'56"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  Pointer class for @AC_canMessage class                   *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_AC_5F_canMessage : public acPtr_class {
//--- START OF USER ZONE 2

  public : virtual bool messageDependsOnTask (void) const = 0 ;
  public : virtual bool messageDependsOnMessage (void) const = 0 ;
  public : virtual PMUInt32 getMessageDependanceValue (void) const = 0 ;

//--- END OF USER ZONE 2

//--- Attributes

//--- Constructor
  public : cPtr_AC_5F_canMessage (LOCATION_ARGS) ;

//--- Attribute accessors
//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const = 0 ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const = 0 ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const = 0 ;

} ;

